# Generated by Django 3.2.5 on 2021-07-19 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddit', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('post_title_last_timestamp', models.FloatField(blank=True, null=True)),
                ('comments_last_timestamp', models.FloatField(blank=True, null=True)),
                ('first_scraped', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TickerInfoBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('ticker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_info', to='reddit_scraper.ticker')),
            ],
        ),
        migrations.CreateModel(
            name='FrequencyEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField()),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequency_entries', to='reddit_scraper.subreddit')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequency_entries', to='reddit_scraper.ticker')),
            ],
        ),
    ]
