# Generated by Django 3.2.5 on 2021-07-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='first_scraped',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
